clc; close all;

this_dir = fileparts(mfilename('fullpath'));
addpath(fullfile(this_dir, 'common'));

cfg = setup_explanatory_figures();

fig = figure('visible', 'off');
set(fig, 'position', [100, 100, 1200, 760]);

ax = axes('Position', [0 0 1 1]);
hold(ax, 'on');
axis(ax, [0 1 0 1]);
axis(ax, 'off');

% --- colors ---
colFeti   = [0.86, 0.92, 0.98];   % light pastel blue
colBddc   = [0.89, 0.95, 0.87];   % light pastel green
colShared = [0.95, 0.95, 0.95];   % light gray
colEdge   = [0.18, 0.18, 0.18];
colArrow  = [0.28, 0.28, 0.28];
colText   = [0.12, 0.12, 0.12];

% --- layout ---
w = 0.28;
h = 0.10;

xL = 0.10;
xR = 0.62;

y1 = 0.76;
y2 = 0.56;
y3 = 0.36;
y4 = 0.16;

xcL = xL + w/2;
xcR = xR + w/2;

% --- titles ---
text(xcL, 0.93, 'FETI-DP', ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'Color', colText);

text(xcL, 0.89, 'dual formulation', ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 11, ...
    'Color', colText);

text(xcR, 0.93, 'BDDC', ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'Color', colText);

text(xcR, 0.89, 'primal preconditioner', ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 11, ...
    'Color', colText);

% ============================================================
% Left column: FETI-DP
% ============================================================
rectangle('Position', [xL, y1, w, h], ...
    'Curvature', 0.02, ...
    'FaceColor', colFeti, ...
    'EdgeColor', colEdge, ...
    'LineWidth', 1.2);
text(xcL, y1 + h/2, ...
    {'product interface space', 'W_\Delta and jump operator B_\Delta'}, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 12, ...
    'Color', colText);

rectangle('Position', [xL, y2, w, h], ...
    'Curvature', 0.02, ...
    'FaceColor', colFeti, ...
    'EdgeColor', colEdge, ...
    'LineWidth', 1.2);
text(xcL, y2 + h/2, ...
    {'Lagrange multipliers \lambda', 'enforce interface continuity'}, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 12, ...
    'Color', colText);

rectangle('Position', [xL, y3, w, h], ...
    'Curvature', 0.02, ...
    'FaceColor', colFeti, ...
    'EdgeColor', colEdge, ...
    'LineWidth', 1.2);
text(xcL, y3 + h/2, ...
    {'local subdomain solves', '+ primal / coarse solve'}, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 12, ...
    'Color', colText);

rectangle('Position', [xL, y4, w, h], ...
    'Curvature', 0.02, ...
    'FaceColor', colFeti, ...
    'EdgeColor', colEdge, ...
    'LineWidth', 1.2);
text(xcL, y4 + h/2, ...
    {'dual iteration / interface correction', 'and reconstructed solution'}, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 12, ...
    'Color', colText);

% ============================================================
% Right column: BDDC
% ============================================================
rectangle('Position', [xR, y1, w, h], ...
    'Curvature', 0.02, ...
    'FaceColor', colBddc, ...
    'EdgeColor', colEdge, ...
    'LineWidth', 1.2);
text(xcR, y1 + h/2, ...
    {'assembled interface residual', 'on the primal interface space'}, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 12, ...
    'Color', colText);

rectangle('Position', [xR, y2, w, h], ...
    'Curvature', 0.02, ...
    'FaceColor', colBddc, ...
    'EdgeColor', colEdge, ...
    'LineWidth', 1.2);
text(xcR, y2 + h/2, ...
    {'local subdomain corrections', 'with primal constraints'}, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 12, ...
    'Color', colText);

rectangle('Position', [xR, y3, w, h], ...
    'Curvature', 0.02, ...
    'FaceColor', colBddc, ...
    'EdgeColor', colEdge, ...
    'LineWidth', 1.2);
text(xcR, y3 + h/2, ...
    {'primal / coarse correction', 'shared across subdomains'}, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 12, ...
    'Color', colText);

rectangle('Position', [xR, y4, w, h], ...
    'Curvature', 0.02, ...
    'FaceColor', colBddc, ...
    'EdgeColor', colEdge, ...
    'LineWidth', 1.2);
text(xcR, y4 + h/2, ...
    {'averaging of local corrections', 'and interface correction'}, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 12, ...
    'Color', colText);

% ============================================================
% Vertical arrows
% ============================================================
arrow_drop = 0.08;

quiver(xcL, y1, 0, -arrow_drop, 0, ...
    'Color', colArrow, 'LineWidth', 1.6, 'MaxHeadSize', 0.35);
quiver(xcL, y2, 0, -arrow_drop, 0, ...
    'Color', colArrow, 'LineWidth', 1.6, 'MaxHeadSize', 0.35);
quiver(xcL, y3, 0, -arrow_drop, 0, ...
    'Color', colArrow, 'LineWidth', 1.6, 'MaxHeadSize', 0.35);

quiver(xcR, y1, 0, -arrow_drop, 0, ...
    'Color', colArrow, 'LineWidth', 1.6, 'MaxHeadSize', 0.35);
quiver(xcR, y2, 0, -arrow_drop, 0, ...
    'Color', colArrow, 'LineWidth', 1.6, 'MaxHeadSize', 0.35);
quiver(xcR, y3, 0, -arrow_drop, 0, ...
    'Color', colArrow, 'LineWidth', 1.6, 'MaxHeadSize', 0.35);

% ============================================================
% Shared coarse-space relation
% ============================================================
plot([xL + w, xR], [y3 + h/2, y3 + h/2], '--', ...
    'Color', [0.45, 0.45, 0.45], ...
    'LineWidth', 1.2);

text(0.50, y3 + h/2 + 0.035, 'shared primal / coarse space', ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 11, ...
    'Color', [0.35, 0.35, 0.35]);

% ============================================================
% Bottom shared note
% ============================================================
rectangle('Position', [0.27, 0.03, 0.46, 0.07], ...
    'Curvature', 0.02, ...
    'FaceColor', colShared, ...
    'EdgeColor', [0.55, 0.55, 0.55], ...
    'LineWidth', 1.0);

text(0.50, 0.065, ...
    {'Both methods use the same subdomain decomposition', ...
     'and the same primal constraints, but differ in how continuity is handled.'}, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 11, ...
    'Color', colText);

filename = fullfile(cfg.outdir, 'fig_5_1_feti_bddc_scheme');
save_thesis_figure(fig, filename);
close(fig);